-- Insight engine: per-tenant weekly strategic digest.
-- Generated by Sunday 07:00 UTC cron; stored once per tenant per Saturday-anchored week.
-- Rules engine + LLM synthesis over intel_cards, trend_scouts, own_post_metrics,
-- keyword_rankings, leads, campaigns.

create table if not exists weekly_digests (
  id uuid primary key default gen_random_uuid(),
  tenant_slug text not null references tenants(slug) on delete cascade,
  week_of date not null,          -- Saturday-anchored week
  strategic_brief text,
  top_competitor_moves jsonb not null default '[]',
  -- shape: [{ intel_card_id, competitor_name, platform, content_type, why_notable, multiplier }]
  winning_formats jsonb not null default '[]',
  -- shape: [{ format, platform, evidence, multiplier }]
  recommended_actions jsonb not null default '[]',
  -- shape: [{ priority, action, target_module, rationale }]
  own_performance jsonb not null default '{}',
  -- shape: { posts_this_week, reach_this_week, reach_prior_week, pct_change, top_post?, worst_post? }
  seo_summary jsonb not null default '{}',
  -- shape: { tracked_total, rising, declining, avg_position, avg_position_change, new_top10 }
  leads_summary jsonb not null default '{}',
  -- shape: { total_active, new_warm, needs_followup, converted_this_week }
  generator_model text,
  generator_cost_usd numeric(8,4) not null default 0,
  generated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create unique index if not exists uq_weekly_digests_tenant_week
  on weekly_digests(tenant_slug, week_of);

create index if not exists idx_weekly_digests_tenant_generated
  on weekly_digests(tenant_slug, generated_at desc);

alter table weekly_digests enable row level security;

drop policy if exists "members access weekly_digests" on weekly_digests;
create policy "members access weekly_digests" on weekly_digests
  for all using (public.is_tenant_member(tenant_slug))
  with check (public.is_tenant_member(tenant_slug));
